#!/usr/bin/bash
field=$1
outname=$2

python run_mcsed_fit.py -tf $field -o $outname.dat -no 4 -p
mkdir output/$2
mv output/*.dat output/$outname
mv output/*.png output/$outname
mv output/*$outname* output/$outname